### ISSUE TITLE
有没有数据库初始化sql

### ISSUE THREAD

**Issue by X-Mars** [IYFY/table_tennis_backend#1]
大佬你好，
想试用下该项目，请问有没有数据库初始化sql啊。
谢谢

**Comment by IYFY** [comment]
请查看附件数据导入sql文件和数据库字段的简单描述。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IYFY/table_tennis_backend"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月12日(星期三) 晚上7:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[IYFY/table_tennis_backend] 有没有数据库初始化sql (Issue #1)





 
大佬你好，
 想试用下该项目，请问有没有数据库初始化sql啊。
 谢谢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by X-Mars** [comment]
感谢大佬的回复，我没在项目里找到附件sql。

**Comment by IYFY** [comment]
在邮箱附件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IYFY/table_tennis_backend"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月13日(星期四) 晚上9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IYFY/table_tennis_backend] 有没有数据库初始化sql (Issue #1)





 
感谢大佬的回复，我没在项目里找到附件sql。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by X-Mars** [comment]
邮件里面没有附件，方便直接发到我的邮箱吗 
xtlyk@163.com
谢谢
